### ISSUE TITLE
Euro in Britain?!

### ISSUE THREAD

**Issue by szabolcs-szilagyi** [Jeger/unamerican-jquery#6]
Should change the example code:
`€('#greatBritain').mouseLeave(() => { console.log('Make the EU great again'); });`

In Britain they still use british pound and don't think they will change anytime soon. :)

**Comment by halvardos** [comment]
Yeah, you are right of course. Do you have a suggestion for something funny?

**Comment by szabolcs-szilagyi** [comment]
Would suggest Cyprus or Luxembourg. They are the 7th and 8th smallest country in Europe, that are part of the EU. Could also be Monaco, they also use euro, but they are not part of the EU.
Think Monaco could be the funniest, not sure how would a resident of Monaco would think about it though. :)

**Comment by halvardos** [comment]
@szabolcs-szilagyi do you want to create a PR?

**Comment by szabolcs-szilagyi** [comment]
@Jeger Sure, will have a look during the weekend.

**Comment by halvardos** [comment]
@szabolcs-szilagyi Awesome man! I could do it myself, but i really want others to get invested in this 👯

**Comment by joneskoo** [comment]
Alternatively could look into using EU flag emoji 🇪🇺 instead of a currency symbol.
